/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type IndustryType =
  | 'delivery'
  | 'school'
  | 'clinic'
  | 'hotel'
  | 'real_estate'
  | 'sacco'
  | 'retail'
  | 'restaurant'
  | 'hardware'
  | 'security'
  | 'software'
  | 'law_firm'
  | 'automotive'
  | 'beauty_spa'
  | 'clean_energy'
  | 'agribusiness'
  | 'fitness_gym'
  | 'tourism_safari'
  | 'events_decor'
  | 'waste_mgmt'
  | string;

export type SubscriptionPlan = 'starter' | 'professional' | 'enterprise';

export type UserRole = 'super_admin' | 'business_owner' | 'staff' | 'customer';

export interface Tenant {
  tenant_id: string;
  company_name: string;
  industry_type: IndustryType;
  subscription_plan: SubscriptionPlan;
  subscription_status: 'active' | 'past_due' | 'trial';
  created_at: string;
  // Dynamic brand customization settings
  logo_url?: string;
  custom_ai_instructions?: string;
  physical_address?: string;
  phone_number?: string;
  email_address?: string;
}

export interface User {
  id: string;
  tenant_id: string | null; // null for super-admins
  name: string;
  email: string;
  role: UserRole;
  created_at: string;
}

export interface Customer {
  id: string;
  tenant_id: string;
  name: string;
  phone: string;
  email: string;
  lead_score: number; // 0-100 autogenerated
  created_at: string;
}

export interface Lead {
  id: string;
  tenant_id: string;
  customer_id: string;
  status: 'new' | 'contacted' | 'negotiation' | 'won' | 'lost';
  interest: string;
  estimated_value: number; // in UGX
  score: number;
  summary: string;
  created_at: string;
}

export interface Conversation {
  id: string;
  tenant_id: string;
  customer_id: string;
  channel: 'whatsapp' | 'telegram' | 'webchat' | 'sms' | 'email';
  last_message: string;
  updated_at: string;
  status: 'active' | 'resolved' | 'handed_over';
}

export interface Message {
  id: string;
  conversation_id: string;
  sender: 'customer' | 'ai' | 'agent';
  content: string;
  timestamp: string;
  metadata?: {
    tool_calls?: {
      name: string;
      args: any;
      result?: any;
    }[];
    workflow_triggered?: string;
    extracted_data?: any;
  };
}

export interface KnowledgeBaseItem {
  id: string;
  tenant_id: string;
  name: string;
  type: 'pdf' | 'docx' | 'txt' | 'csv' | 'url';
  content_url?: string;
  text_preview: string;
  chunk_count: number;
  created_at: string;
}

export interface WorkflowNode {
  id: string;
  label: string;
  type: 'trigger' | 'action' | 'condition';
  description: string;
}

export interface WorkflowEdge {
  from: string;
  to: string;
}

export interface Workflow {
  id: string;
  tenant_id: string;
  name: string;
  trigger_event: string; // e.g., "customer_requests_delivery"
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  is_active: boolean;
  created_at: string;
}

export interface Order {
  id: string;
  tenant_id: string;
  customer_id: string;
  pickup_address: string;
  dropoff_address: string;
  package_details: string;
  distance_km: number;
  duration_mins: number;
  fare_ugx: number;
  status: 'pending' | 'assigned' | 'in_transit' | 'completed' | 'cancelled';
  rider_id: string | null;
  created_at: string;
}

export interface Rider {
  id: string;
  tenant_id: string;
  name: string;
  phone: string;
  status: 'available' | 'busy' | 'offline';
  latitude: number;
  longitude: number;
  created_at: string;
}

export interface Payment {
  id: string;
  tenant_id: string;
  amount: number;
  currency: 'UGX' | 'USD';
  method: 'mtn_momo' | 'airtel_money' | 'stripe';
  status: 'success' | 'pending' | 'failed';
  reference: string;
  created_at: string;
}

export interface AnalyticsSummary {
  total_tenants: number;
  total_revenue_ugx: number;
  ai_api_calls: number;
  active_customers: number;
  active_conversations: number;
  total_orders: number;
  total_leads: number;
  conversations_by_channel: {
    whatsapp: number;
    telegram: number;
    webchat: number;
    sms: number;
    email: number;
  };
  by_industry: {
    [key in IndustryType]?: number;
  };
}

export interface IndustryTemplate {
  id: string;
  name: string;
  terminology: string[];
  services: string[];
  faqs: { question: string; answer: string }[];
  suggested_responses: string[];
  actions: string[];
  lead_capture_fields: string[];
  ai_instructions: string;
}
